<?php error_reporting(0);

?>
<head>
<link rel="stylesheet" href="/css/bootstrap.css">
<link rel="stylesheet" href="/css/layout.css">
</head>
<body style="background-image:url('images/grid_bg.gif')">
<div class="navbar navbar-fixed-top">  
<div class="navbar-inner">  
<div class="container">  
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
<span class="icon-bar"></span>  
</a>  

<div class="nav-collapse">  
<ul class="nav">  
<li><a class="brand" href="#">Zend App.....!!!!!</a></li>  
<li><a></a></li>  
<li><a></a></li>  
</ul>  
</div><!--/.nav-collapse -->  
</div>  
</div>  
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>  
<div class="container">  
<!-- Main hero unit for a primary marketing message or call to action -->  
<div class="leaderboard" style="margin-top:80px;">  
<h1></h1>  
</div> 

<!-- Example row of columns -->  
<div class="row" style="margin-top:80px;">  

<div class="span4">  
<h2>Login Through Facebook</h2>  
<p></p>  
<p><a class="btn btn-success btn-large" href="<?php echo $this->data['login_url']; ?>">CONNECT WITH FACEBOOK</a></p>  
</div>  
<div class="span4">  
<h2>Login Through Twitter</h2>  
<p></p>  
<p><a class="btn btn-success btn-large" href="<?php echo $this->data['link']; ?>">CONNECT WITH TWITTER</a></p>  
</div>  
<div class="span4">  
<h2>Login Through Google</h2>  
<p></p>  
<p><a class="btn btn-success btn-large" href="<?php echo $this->data['authUrl']; ?>">CONNECT WITH GOOGLE</a></p>  
</div>

</div> 
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>   
<br>
<br>
<br>
<br> <br>
<br>
<br>
<br> 
<br> <br>
<br>
<br>
<br>
<hr>  
<footer>  
<p></p>  
</footer>  
</div> <!-- /container --> 
</body>